// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHOjPaUWprsG_V61lRa9QzbjC8GbdmRtY',
    appId: '1:747739641063:web:ab728f5209bd3ee8d15e42',
    messagingSenderId: '747739641063',
    projectId: 'greenfundconnect',
    authDomain: 'greenfundconnect.firebaseapp.com',
    storageBucket: 'greenfundconnect.firebasestorage.app',
    measurementId: 'G-090B2B8XD0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBir5-N24K-7zemoRd_vQ2Sl_LdoDkfs2Q',
    appId: '1:747739641063:android:d704503f855c3178d15e42',
    messagingSenderId: '747739641063',
    projectId: 'greenfundconnect',
    storageBucket: 'greenfundconnect.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXAyoqTrMrnj73snW7E_mwYJd57BsTFo0',
    appId: '1:747739641063:ios:38dc08bb042caa62d15e42',
    messagingSenderId: '747739641063',
    projectId: 'greenfundconnect',
    storageBucket: 'greenfundconnect.firebasestorage.app',
    iosBundleId: 'com.example.greenfundConnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXAyoqTrMrnj73snW7E_mwYJd57BsTFo0',
    appId: '1:747739641063:ios:38dc08bb042caa62d15e42',
    messagingSenderId: '747739641063',
    projectId: 'greenfundconnect',
    storageBucket: 'greenfundconnect.firebasestorage.app',
    iosBundleId: 'com.example.greenfundConnect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCHOjPaUWprsG_V61lRa9QzbjC8GbdmRtY',
    appId: '1:747739641063:web:d76ba6401d3f17dbd15e42',
    messagingSenderId: '747739641063',
    projectId: 'greenfundconnect',
    authDomain: 'greenfundconnect.firebaseapp.com',
    storageBucket: 'greenfundconnect.firebasestorage.app',
    measurementId: 'G-41191GEH8H',
  );
}
